#método para operar strings
cadena = input("Escribe una caena de texto: ")
print("La cadena en mayúsculas es:", cadena.upper())
print("La cadena en minúsculas es:", cadena.lower())
print("La cadena con la primera letra en mayúscula es:", cadena.capitalize())
print("La cadena con cada palabra iniciando en mayúscula es:", cadena.title())
print("La cadena con las vocales en mayúsculas es:", cadena.replace("a","A").replace("e","E").replace("i","I").replace("o","O").replace("u","U"))
print("La cadena con las consonantes en mayúscula es:", cadena.replace("b","B").replace("c","C").replace("d","D").replace("f","F"))
print("La cadena con las vocales en minúsculas es:", cadena.replace("A","a").replace("E","e").replace("I","i").replace("O","o").replace("U","u"))
print("La cadena con las consonantes en minúsculas es:", cadena.replace("B","b"))
print("La cadena con espacios eliminados al inicio y al final es:", cadena.strip())
print("La cadena con espacios eliminados al inicio es:", cadena.lstrip())
print("La cadena con espacios eliminados al final es:", cadena.rstrip())
print("La cadena eliminando todos los espacios es:", cadena.replace(" ", ""))